name: "Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  github_tagged_release:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: "action/checkout@v2"
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "15"
          cache: "npm"

      - name: Install dependencies
        run: "npm ci"

      - name: Run Build
        run: "npm run build"

      - name: Create Changelog and create release-ticket in Yandex.Tracker
        run: "./scripts/generate_changelog.sh |& ./scripts/create_ticket.sh"
        env:
          YANDEX_OAUTH: ${{ secrets.OAUTH}}
          YANDEX_ORGID: ${{ secrets.ORGID}}
          YANDEX_QUEUE: TMP

      - name: Run tests and create comment in release-ticket
        run: "CI=true npm test |& ./scripts/create_comment.sh"
        env:
          YANDEX_OAUTH: ${{ secrets.OAUTH}}
          YANDEX_ORGID: ${{ secrets.ORGID}}
          YANDEX_QUEUE: TMP
