---
name: "tagged release"

on:
  push:
    tags:
      - "v*"

jobs:
  github_tagged_release:
    runs-on: "ubuntu-20.04"
    env:
      AUTHOR: "NAIL ISKHAKOV"
      OAUTH_TRACKER: ${{ secrets.OAUTH_YANDEX_TRACKER }}

    steps:
      - uses: "action/checkout@v2"
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "15"
          cache: "npm"

      - run: "npm ci"

      - run: "npm run build"

      - run: "./scripts/generate_changelog.sh |& ./scripts/create_ticket.sh"

      - run: "CI=true npm test |& ./scripts/create_comment.sh"
